cpu_usage:
  query: (avg(irate(node_cpu_seconds_total{instance=~"$instance",mode="user"}[1m]))) * 100
  instance_from: node
memory_usage:
  query: node_memory_MemTotal_bytes{instance=~"$instance"} - (node_memory_Cached_bytes{instance=~"$instance"} + node_memory_Buffers_bytes{instance=~"$instance"} + node_memory_MemFree_bytes{instance=~"$instance"})
  instance_from: node
cpu_metrics:
  - query: node_scrape_collector_duration_seconds{instance="$instance"}
    instance_from: node
  - query: node_procs_running{instance="$instance"}
    instance_from: node
  - query: node_procs_blocked{instance="$instance"}
    instance_from: node
  - query: node_entropy_available_bits{instance="$instance"}
    instance_from: node
  - query: node_load1{instance="$instance"}
    instance_from: node
  - query: node_load5{instance="$instance"}
    instance_from: node
  - query: node_load15{instance="$instance"}
    instance_from: node
  - query: pg_settings_random_page_cost{instance=~"$instance"}
    instance_from: postgresql
  - query: pg_settings_max_worker_processes{instance=~"$instance"}
    instance_from: postgresql
  - query: pg_settings_max_parallel_workers{instance=~"$instance"}
    instance_from: postgresql
  - query: pg_stat_activity_count{instance=~"$instance", state="active"} !=0
    instance_from: postgresql
  - query: pg_locks_count{instance=~"$instance"} != 0
    instance_from: postgresql
  - query: pg_stat_database_tup_returned{instance=~"$instance"} != 0
    instance_from: postgresql
  - query: pg_stat_activity_count{instance=~"$instance", state=~"idle|idle in transaction|idle in transaction (aborted)"}
    instance_from: postgresql
memory_metrics:
  - query: irate(node_disk_write_time_seconds_total{instance=~"$instance"}[1m])
    instance_from: node
  - query: node_memory_Inactive_anon_bytes{instance="$instance"}
    instance_from: node
  - query: node_memory_MemFree_bytes{instance="$instance"}
    instance_from: node
  - query: node_memory_Buffers_bytes{instance="$instance"}
    instance_from: node
  - query: node_memory_Cached_bytes{instance="$instance"}
    instance_from: node
  - query: node_memory_MemAvailable_bytes{instance="$instance"}
    instance_from: node
  - query: node_memory_Dirty_bytes{instance="$instance"}
    instance_from: node
  - query: pg_stat_activity_count{instance=~"$instance", state="active"} !=0
    instance_from: postgresql
  - query: pg_settings_shared_buffers_bytes{instance="$instance"}
    instance_from: postgresql
  - query: pg_settings_effective_cache_size_bytes{instance="$instance"}
    instance_from: postgresql
  - query: pg_settings_maintenance_work_mem_bytes{instance="$instance"}
    instance_from: postgresql
  - query: pg_settings_work_mem_bytes{instance="$instance"}
    instance_from: postgresql
  - query: pg_settings_max_wal_size_bytes{instance="$instance"}
    instance_from: postgresql
  - query: irate(pg_stat_bgwriter_buffers_alloc{instance="$instance"}[5m])
    instance_from: postgresql
  - query: irate(pg_stat_bgwriter_buffers_backend_fsync{instance="$instance"}[5m])
    instance_from: postgresql
  - query: irate(pg_stat_bgwriter_buffers_checkpoint{instance="$instance"}[5m])
    instance_from: postgresql
  - query: irate(pg_stat_bgwriter_buffers_clean{instance="$instance"}[5m])
    instance_from: postgresql
  - query: irate(pg_stat_database_conflicts{instance="$instance"}[5m])
    instance_from: postgresql
  - query: irate(pg_stat_database_deadlocks{instance="$instance"}[5m])
    instance_from: postgresql
network_metrics:
  - query: node_sockstat_TCP_tw{instance="$instance"}
    instance_from: node
  - query: node_sockstat_TCP_orphan{instance="$instance"}
    instance_from: node
  - query: node_sockstat_TCP_tw{instance=~'$instance'}
    instance_from: node
  - query: irate(node_netstat_Tcp_PassiveOpens{instance=~'$instance'}[1m])
    instance_from: node
  - query: node_sockstat_TCP_alloc{instance=~'$instance'}
    instance_from: node
  - query: node_sockstat_TCP_inuse{instance=~'$instance'}
    instance_from: node
io_metrics:
  - query: SUM(pg_stat_database_tup_fetched{instance=~"$instance"})
    instance_from: postgresql
  - query: SUM(pg_stat_database_tup_inserted{instance=~"$instance"})
    instance_from: postgresql
  - query: SUM(pg_stat_database_tup_updated{instance=~"$instance"})
    instance_from: postgresql
  - query: process_open_fds{instance="$instance"}
    instance_from: postgresql
  - query: irate(pg_stat_database_xact_commit{instance="$instance"}[5m])
    instance_from: postgresql
  - query: irate(pg_stat_database_xact_rollback{instance="$instance"}[5m])
    instance_from: postgresql
  - query: pg_stat_database_tup_updated{instance=~"$instance"} != 0
    instance_from: postgresql
  - query: pg_stat_database_blks_hit{instance="$instance"} / (pg_stat_database_blks_read{instance="$instance"} + pg_stat_database_blks_hit{instance="$instance"})
    instance_from: postgresql
  - query: irate(pg_stat_database_temp_bytes{instance="$instance"}[5m])
    instance_from: postgresql
  - query: irate(pg_stat_bgwriter_checkpoint_write_time{instance="$instance"}[5m])
    instance_from: postgresql
  - query: irate(pg_stat_bgwriter_checkpoint_sync_time{instance="$instance"}[5m])
    instance_from: postgresql
  - query: node_filesystem_size_bytes{instance=~'$instance',fstype=~"ext4|xfs"}-node_filesystem_avail_bytes {instance=~'$instance',fstype=~"ext4|xfs"}
    instance_from: node
  - query: node_filesystem_size_bytes{instance=~'$instance',fstype=~"ext4|xfs"}
    instance_from: node
  - query: 1-(node_filesystem_free_bytes{instance=~'$instance',fstype=~"ext4|xfs"} / node_filesystem_size_bytes{instance=~'$instance',fstype=~"ext4|xfs"})
    instance_from: node
  - query: irate(node_disk_reads_completed_total{instance=~"$instance"}[1m])
    instance_from: node
  - query: irate(node_disk_writes_completed_total{instance=~"$instance"}[1m])
    instance_from: node
  - query: node_disk_io_now{instance=~"$instance"}
    instance_from: node
  - query: irate(node_disk_read_bytes_total{instance=~"$instance"}[1m])
    instance_from: node
  - query: irate(node_disk_written_bytes_total{instance=~"$instance"}[1m])
    instance_from: node
  - query: irate(node_disk_io_time_seconds_total{instance=~"$instance"}[1m])
    instance_from: node
  - query: irate(node_disk_io_time_weighted_seconds_total{instance=~"$instance"}[1m])
    instance_from: node
  - query: irate(node_disk_read_time_seconds_total{instance=~"$instance"}[1m])
    instance_from: node
  - query: irate(node_disk_write_time_seconds_total{instance=~"$instance"}[1m])
    instance_from: node
  - query: irate(node_disk_io_time_seconds_total{instance=~"$instance"}[1m])
    instance_from: node