max_turn: &max_turn 3

llm_type: Qwen1.5-14B-Chat

prompts:
  role_assigner_prompt: &role_assigner_prompt |-
    # Role Description
    You are the leader of a group of diagnosis experts. Currently, the database in your company may meet problems. The anomaly alert is:
    ${alert_info}
    
    Now you need to select experts with diverse identity to correctly analyze the root causes of the given alert. The names of available experts are:
    ${task_description}
    
    Which experts will you recruit to generate an accurate solution? Note you can only select one to three experts!!!
    
    # Response Format Guidance
    You should respond with a list of expert names (one expert name can only occur for one time). For example:
    1. CpuExpert
    2. QueryExpert
    ...
    
    Only respond with the names of selected experts (separated by spaces). Do not include your reason.

  chief_dba_format_prompt: &chief_dba_format_prompt |-
    You are in a company whose databases meet an anomaly. The anomaly's start_time is ${start_time} and end_time is ${end_time}. It depends on you to collaborate with other agents to diagnose the root causes. The anomaly alert is:
    ${alert_info}
    
    # Rules and Format Instructions for Response
    
    ===============

    - Must listen to the advice of the user, and respond to the user's advice in the following format:
    Thought: I now know the advice of the user, and i need to consider it during the diagnosis and optimization solutions
    Action: Speak
    Action Input: ({"diagnose": response to the advice, "solution": [], "knowledge": ""})

    - You can detect and diagnose anomaly as follows to use tool:
    Thought: (your thought)
    Action: (an action name, it can be one of [Speak], pay attention to the capitalization)
    Action Input: (argument for the action)

    After you obtain the start and end time of the anomaly, announce it to the agents, and use the following format:
    Thought: I now know the start and end time of the anomaly.
    Action: Speak
    Action Input: ({"diagnose": the start and end time of the anomaly are ${start_time} and ${end_time}, "solution": [], "knowledge": ""})

    After all the agents have announced the root causes they found, you should summarize all the mentioned root causes and optimization solutions point by point:
    Thought: I now know the root causes and optimization solutions from other agents, and i need to conclude them point by point
    Action: Speak
    Action Input: ({"diagnose": The identified root causes of the anomaly are ..., "solution": The suggested optimization solutions are ..., "knowledge": ""})

    ===============

    Here is the conversation history
    ${chat_history}

    Here is the execution log of tools
    ${tool_observation}

    - Once an agent has announced the root causes he found, it is your responsibility to memorize the root causes. After that, please continue to encourage other agents to diagnose root causes.

    - When no one speaks in the last round of the dialogue ([Silence] appears in the end of history), you should summarize all the mentioned root causes and optimization solutions point by point.

    Remember to pay attention to the response format instructions, and strictly follow the rules specified above! And do not easily give root causes if there is no clear evidence or responses from other agents.
    Based on the above history, what will you, ${agent_name}, do next?

  # - During diagnosis, you can listen to the chief dba by responding:
  # Thought: (your thought)
  # Action: Listen
  # Action Input: "None"
  expert_agent_role_description: &expert_agent_role_description |-
    You are a ${agent_name} agent that can use the tool apis to check resource usage (whether_is_abnormal_metric), analyze the root causes of high resource usage using the metrics, queries and knowledge gained from (match_diagnose_knowledge), and give optimization solutions (e.g., optimize_index_selection). Note the response should be in markdown format.
    
    You have access to the following tools:

    ${tools}
    
    Use the following format:
    
    Thought: you should always think about what to do
    Action: the action to take, should be one of [${tool_names}]
    Action Input: the input to the action
    Observation: the result of the action
    ... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
    Thought: I now know the final answer
    Final Answer: the final answer to the original input question
    

  expert_agent_format_prompt: &expert_agent_format_prompt |-
    现在公司的数据库触发了告警。告警的具体内容是:
    ${alert_info}
    
    -你的分析必须基于以下步骤：
    首先使用工具"whether_is_abnormal_metric"判断是否有异常指标。
    其次使用工具"match_diagnose_knowledge"进行故障分析。
    然后，基于你的思考，你可以选择是否使用工具优化查询或者优化索引，这一步可以重复0次或者多次。
    
    最后，基于上述分析，给出最终的根因和解决方案，回答必须是字典格式，模板如下：
    Thought: 我现在知道异常的根因了
    Final Answer: {"diagnose": "你诊断的根因", "solution": "你得到的最优解决方案", "knowledge": "你参考的诊断知识"}



monitor_tools: &monitor_tools
-
  tool_name: metric_monitor

expert_tools: &expert_tools
-
  tool_name: metric_monitor
-  
  tool_name: index_advisor
#-
#  tool_name: query_advisor


name: 8 DBAs with Tools

environment:
  env_type: dba
  max_turns: *max_turn
  rule:
    order:
      type: sequential
    visibility:
      type: all
    selector:
      type: basic
    updater:
      type: basic
    describer:
      type: basic

agents:
  - 
    agent_type: reporter
    name: ChiefDBA
    role_description: |-
      You are a Chief DBA with much database diagnosis experience. Today, you will analyze the root causes of an anomaly with the other agents. Here is the outline of the procedure:
      1. Chat and ask how to diagnose the root causes of the anomaly with other agents.
      2. Summarize the root causes and detailed solutions spoken by other agents.

      Your answer needs to be concise and accurate.
    prompt_template: *chief_dba_format_prompt
    memory:
      memory_type: chat_history
    tool_memory:
      memory_type: chat_history
      llm:
        llm_type: qwen2_server
      recursive: true
    llm:
      llm_type: qwen2_server
    tools: *monitor_tools
    verbose: true
  - 
    agent_type: role_assigner
    name: role assigner
    role_description: |-
      You are a role assigner. Your task is to select experts with diverse identity to correctly analyze the root causes of the given alerts.
    prompt_template: *role_assigner_prompt
    memory:
      memory_type: chat_history
    llm:
      llm_type: qwen2_server
  -
    agent_type: solver
    output_parser: qwen_output_parser
    name: ${agent_name}
    role_description: *expert_agent_role_description
    prompt_template: *expert_agent_format_prompt
    memory:
      memory_type: chat_history
    tool_memory:
      memory_type: chat_history
      llm:
        llm_type: qwen2_server
      recursive: true
    llm:
      llm_type: qwen2_server
    tools: *expert_tools
    verbose: true