version: '3'
services:

  postgres_db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: Test123_456
      POSTGRES_DB: sysbench
networks:
  default:
    name: agent_network
