// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomInputContainer: typeof import('./../src/components/BottomInputContainer.vue')['default']
    ChatItem: typeof import('./../src/components/ChatItem.vue')['default']
    Code_demo: typeof import('./../src/components/code_demo.vue')['default']
    DatabaseChart: typeof import('./../src/components/DatabaseChart.vue')['default']
    DatabaseChatItem: typeof import('./../src/components/DatabaseChatItem.vue')['default']
    DataflowDataShow: typeof import('./../src/components/DataflowDataShow.vue')['default']
    ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
    KnowledgeChatItem: typeof import('./../src/components/KnowledgeChatItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
  }
}
