route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'db-gpt'
receivers:
  - name: 'db-gpt'
    webhook_configs:
      - url: 'http://172.27.58.65:8023/alert/alert'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']